# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
inhibit_all_warnings!
target 'GeSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GeSwift
  pod 'WCDB.swift'
  pod 'Kingfisher'
  pod 'CryptoSwift'
  pod 'SnapKit'
  pod 'Schedule'
  pod 'SwiftyJSON'
#  pod 'IJKMediaFramework', :path => 'IJKMediaFramework/'

  target 'GeSwiftTests' do
    inherit! :search_paths

  end
end
