# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GeSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GeSwift
  pod 'WCDB.swift'
  pod 'Kingfisher'
  pod 'CryptoSwift'
  pod 'SnapKit'
  pod 'Schedule'

end
